spring:
  application:
    name: SpringBoot
  data:
    mongodb:
      uri: mongodb+srv://piyushranjan2424:Piyush12345@cluster0.nhcydpi.mongodb.net/?retryWrites=true&w=majority&appName=Cluster0
      database: journaldb
      auto-index-creation: true
  main:
    allow-circular-references: true
server:
  port: 8081
  servlet:
    context-path: /Journal 